name: $(Build.SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
- desarrollo

variables:
 - name: BuildPlatform
   value: 'Any CPU'
 - name: BuildConfiguration
   value: Release
 - name:  BuildParameters.solution
   value: '**/RegistroVotantes.sln'

jobs:
- job: Phase_1
  displayName: 'Integración Continua'
  cancelTimeoutInMinutes: 1
  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-latest'

  steps:
  - checkout: self
    fetchDepth: 1
  - task: NuGetToolInstaller@0
    name: NuGetToolInstaller1
    displayName: Use NuGet

  - task: NuGetCommand@2
    name: NuGetCommand2
    displayName: NuGet restore
    inputs:
      solution: $(BuildParameters.solution)
      
  - task: EPM-Evaluacion-Conectividad-SonarQube@0
    displayName: 'EPM - Evaluación de Conectividad SonarQube '
    inputs:
      SonarQubeInput-ECSQ: 'SonarEPM'

  - task: SonarQubePrepare@4
    displayName: Prepare analysis on SonarQube
    condition: eq(variables['ESTADOSONAR'],1)
    continueOnError: True
    inputs:
      SonarQube: 'SonarEPM'
      projectKey: PruebasDevOps.RegistroVotantes-PruebasAutomatizadas
      projectName: PruebasDevOps - RegistroVotantes-PruebasAutomatizadas
      projectVersion: $(Build.BuildNumber)
      extraProperties: >-
        ## https:\\docs.sonarqube.org\latest\analysis\scan\sonarscanner-for-msbuild\


        /d:sonar.cs.vscoveragexml.reportsPaths=**\ *.coveragexml


        /d:sonar.cs.vstest.reportsPaths=**\*.trx

        sonar.sourceEncoding=UTF-8

        sonar.ws.timeout=600

        sonar.exclusions=""

  - task: VSBuild@1
    name: VSBuild3
    displayName: Build solution
    inputs:
      solution: $(BuildParameters.solution)
      msbuildArgs: /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\" /p:autoparameterizationwebconfigconnectionstrings=false /p:TransformConfigFile=true
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)

  - task: VSTest@2
    displayName: VsTest - testAssemblies
    continueOnError: True
    inputs:
      testAssemblyVer2: >-
        **\RegistroVotantes.*Test*.dll
        **\RegistroVotantes.*PruebasUnitarias*.dll       

        !**\*TestAdapter.dll

        !**\obj\**
      resultsFolder: $(Common.TestResultsDirectory)
      codeCoverageEnabled: true
      otherConsoleOptions: /platform:x64
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
      diagnosticsEnabled: true

  - task: SonarQubeAnalyze@4
    displayName: Run Code Analysis
    condition: eq(variables['ESTADOSONAR'],1)
    continueOnError: True

  - task: EPM-Quality-Gate-Sonar@0
    displayName: EPM - Evaluación del Quality Gate SonarQube
    condition: eq(variables['ESTADOSONAR'],1)
    continueOnError: True
    inputs:
      SonarQubeInput: 'SonarEPM'
  

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact:'
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: 'RegistroVotantes_Artifact'
...
